#!/bin/bash
cd $(dirname $0)/dreams

. env/bin/activate

# for nvcc
export PATH=$PATH:/usr/local/cuda-11.6/bin/

# Offline huggingface
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1

while :; do
	figlet -f slant -w 100 Dreams starting up | lolcat -a -d 5
	export PERSYN_CONFIG='/home/rob/persyn/config/anna.yaml'
	uvicorn dreams:app --port 8001 --host logicoma.s9
	sleep 1
done
