#!/bin/bash
cd $(dirname $0)/dreams

. env/bin/activate

# for nvcc
export PATH=$PATH:/usr/local/cuda-11.6/bin/

while :; do
	figlet -f slant -w 100 Dreams starting up | lolcat -a -d 5
	. ../config/dreams.conf
	uvicorn dreams:app --port ${DREAM_SERVER_PORT} --host ${DREAM_SERVER_HOST}
	sleep 1
done
