#!/bin/bash
cd $(dirname $0)

. chat/slack/env/bin/activate

# flair sentiment analysis and Tacotron2 TTS on the 1070
export CUDA_VISIBLE_DEVICES=2

while :; do
	figlet -f slant -w 100 Slacker starting up | lolcat -a -d 5
	. config/*.conf
	chat/slack/slack.py
	sleep 1
done
