#!/bin/bash
cd $(dirname $0)/dreams/stable-diffusion

. env/bin/activate

# for nvcc
export PATH=$PATH:/usr/local/cuda-11.6/bin/

export CUDA_VISIBLE_DEVICES=0

while :; do
	figlet -f slant -w 100 SDD starting up | lolcat -a -d 5
	. ../../config/dreams.conf
	uvicorn sdd:app --port ${SD_SERVER_PORT} --host ${SD_SERVER_HOST}
	sleep 1
done
