#!/bin/bash

# icecast (will only run one instance)
cd $(dirname $0)
ices2 ices/anna.xml

sudo amixer set PCM 100%

# gtts
cd $(dirname $0)/voice/gtts/

. env/bin/activate

while :; do
	figlet -f slant -w 100 gTTS starting up | lolcat -a -d 5
	. ../../config/*.conf
	uvicorn ${UVICORN_OPTS} gtts_api:app --port ${GTTS_SERVER_PORT} --host ${GTTS_SERVER_HOST}
	sleep 1
done
