#!/bin/bash
if [ "${DEBUG}" ]; then
  DBG="--log-cli-level=DEBUG -vv -s"
else
  DBG="-vv"
fi

PYTHONPATH=src/ PERSYN_CONFIG=config/test.yaml pytest ${DBG} --cov=src/persyn/chat --cov=src/persyn/interaction --cov=src/persyn/utils $*
