'''
Some selected artists, inspired by https://www.notion.so/sgreens/4ca6f4e229e24da6845b6d49e6b08ae7?v=fdf861d1c65d456e98904fe3f3670bd3
'''
artists = [
    'Adrian Tomine',
    'Agostino Arrivabene',
    'Akira Toriyama',
    'Albert Bierstadt',
    'Alberto Seveso',
    'Albrecht Anker',
    'Albrecht Durer',
    'Alexander Jansson',
    'Alexandr Averin',
    'Algernon Blackwood',
    'Alphonse Mucha',
    'Amiet Cuno',
    'Anders Zorn',
    'Andrea Kowch',
    'Andreas Achenbach',
    'Angus McKie',
    'Anka Zhuravleva',
    'Anna Dittmann',
    'Annie Leibovitz',
    'Ansel Adams',
    'Anton Fadeev',
    'Aubrey Beardsley',
    'Banksy',
    'Bastien Lecouffe-Deharme',
    'Bernardo Bellotto',
    'Bert Hardy',
    'Bill Medcalf',
    'Bob Eggleton',
    'Brandon Woelfel',
    'Brian K. Vaughan',
    'Brook Shaden',
    'Bruce Pennington',
    'Canaletto',
    'Caravaggio',
    'Carlo Crivelli',
    'Carne Griffiths',
    'Casey Weldon',
    'Caspar David Friedrich',
    'Charles Addams',
    'Charles Vess',
    'Chie Yoshii',
    'Chiho Aoshima',
    'Chris Claremont',
    'Christophe Vacher',
    'Chuck Close',
    'Clyde Caldwell',
    'Coby Whitmore',
    'Coles Phillips',
    'Cory Loftis',
    'Craig Mullins',
    'Craola',
    'Cyril Rolando',
    'Daniel F. Gerhartz',
    'David Goldblatt',
    'David Inshaw',
    'Dean Ellis',
    'Derek Gores',
    'Diane Arbus',
    'Dino Valls',
    'Donato Giancola',
    'Douglas Smith',
    'Dr. Seuss',
    'Earl Norem',
    'Ed Emshwiller',
    'Edward Hopper',
    'Edward Robert Hughes',
    'Egon Schiele',
    'Eiichiro Oda',
    'Elsa Bleda',
    'Enki Bilal',
    'Ernest Lawson',
    'Ernst Ludwig Kirchner',
    'Esao Andrews',
    'Ethan Van Sciver',
    'Eve Ventrue',
    'Evgeny Lushpin',
    'Farel Dalrymple',
    'Fenghua Zhong',
    'Frank Weston Benson',
    'Frieke Janssens',
    'Gaston Bussiere',
    'Geoff Johns',
    'George Cruikshank',
    'Gian Lorenzo Bernini',
    'Gil Elvgren',
    'Glen Keane',
    'Greg Rutkowski',
    'Gregory Crewdson',
    'Guido Van Helten',
    'Gustave Doré',
    'Guy Billout',
    'Guy Denning',
    'H R Giger',
    'Hans Baldung',
    'Hans Baluschek',
    'Harumi Hironaka',
    'Hayao Miyazaki',
    'Helene Knoop',
    'Hendrik Kerstens',
    'Henri de Toulouse-Lautrec',
    'Henry Justice Ford',
    'Hieronymus Bosch',
    'Hikari Shimoda',
    'Honore Daumier',
    'Igor Morski',
    'Ilya Kuvshinov',
    'Ingrid Baars',
    'Inio Asano',
    'Ismail Inceoglu',
    'Ivan Albright',
    'Ivan Bilibin',
    'Jack Davis',
    'Jakub Rebelka',
    'James Abbott Mcneill Whistler',
    'James Gilleard',
    'Jamie Hewlett',
    'Jan Van Goyen',
    'Jasmine Becket-Griffith',
    'Jean Giraud',
    'Jeremy Mann',
    'Jesper Ejsing',
    'Joachim Beuckelaer',
    'Joaquin Sorolla',
    'Joe Jusko',
    'John Atkinson Grimshaw',
    'John Berkey',
    'John Cassaday',
    'John Frederick Kensett',
    'John James Audubon',
    'John Kenn Mortensen',
    'John Martin',
    'John Philip Falter',
    'John Salminen',
    'Jon Foster',
    'Karol Bak',
    'Katia Chausheva',
    'Kawacy',
    'Kelly Sue Deconnick',
    'Koson Ohara',
    'Leonardo Da Vinci',
    'Lisa Frank',
    'Lois Van Baarle',
    'Louis Wain',
    'Louise Dahl-Wolfe',
    'Lucas Cranach the Elder',
    'Lucian Freud',
    'M. C. Escher',
    'Makoto Shinkai',
    'Marc Davis',
    'Marc Simonetti',
    'Marco Mazzoni',
    'Marius Borgeaud',
    'Martin Ansin',
    'Mary Cassatt',
    'Mary Jane Ansell',
    'Matthias Jung',
    'Maurice Utrillo',
    'Michael Garmash',
    'Mikalojus Konstantinas Ciurlionis',
    'Mike Worrall',
    'Mimmo Rotella',
    'Moebius',
    'Monia Merlo',
    'Naoko Takeuchi',
    'Naoto Hattori',
    'Natalie Shau',
    'Nicola Samori',
    'Nicolas Delort',
    'Nikolay Makovsky',
    'Noboyoshi Araki',
    'Octavio Ocampo',
    'Oleg Oprisco',
    'Paolo Roversi',
    'Pascale Campion',
    'Paul Barson',
    'Paul Gustav Fischer',
    'Paul Pelletier',
    'Peregrine Heathcote',
    'Peter Andrew Jones',
    'Peter Coulson',
    'Peter Elson',
    'Posuka Demizu',
    'Ralph Horsley',
    'Ralph McQuarrie',
    'Ramon Casas',
    'Randolph Caldecott',
    'Raphael Lacoste',
    'Raymond Swanland',
    'Rembrandt Van Rijn',
    'Rene Lalique',
    'Rene Magritte',
    'Rob Gonsalves',
    'Robert Crumb',
    'Robert Hagan',
    'Robert Kirkman',
    'Ron Mueck',
    'Ron Walotsky',
    'Ross Tran',
    'Ruan Jia',
    'Rudolf Ernst',
    'Sandra Chevrier',
    'Santiago Caruso',
    'Sean Yoro',
    'Shaun Tan',
    'Shepard Fairey',
    'Simon Birch',
    'Simon Stålenhag',
    'Sofonisba Anguissola',
    'Stephan Martiniere',
    'Studio Ghibli',
    'Takato Yamamoto',
    'Tara McPherson',
    'Tex Avery',
    'Theo van Rysselberghe',
    'Tim Doyle',
    'Tim Okamura',
    'Tran Nguyen',
    'Tsutomu Nihei',
    'Umberto Boccioni',
    'Valentin De Boulogne',
    'Wadim Kashin',
    'Wayne Thiebaud',
    'Wes Anderson',
    'Yoann Lossel',
    'Yoji Shinkawa',
]

modifiers = [
    'trending on ArtStation',
    'HQ',
    '4k',
    'masterpiece',
    'hyperrealistic'
]
