#!/bin/bash
usage() {
  echo "Usage: $(basename $0) -p 'prompt' -t 'style' -w width -h height -s seed -o outfile" ;
}

SEED=$RANDOM
WIDTH=512
HEIGHT=512
OUTFILE="out.jpg"
STYLE=""

while getopts "p:s:t:w:h:o:?" opt
do
  case "$opt" in
    '?') usage; exit 0 ;;
    'p') PROMPT=${OPTARG} ;;
    's') SEED=${OPTARG} ;;
    't') STYLE=${OPTARG} ;;
    'w') WIDTH=${OPTARG} ;;
    'h') HEIGHT=${OPTARG} ;;
    'o') OUTFILE=${OPTARG} ;;
    *) usage; exit 1 ;;
  esac
done

if [ -z "${PROMPT}" ]; then
  usage
  exit 1
fi

set -e

cd $(dirname $0)

. env/bin/activate

TMPDIR=$(mktemp -d)

export PYTHONPATH=.:taming-transformers:CLIP

if [ ! -z "${STYLE}" ]; then
  export GEN="${PROMPT} by ${STYLE}"
else
  export GEN="${PROMPT}"
fi

python3 optimizedSD/optimized_txt2img.py --H ${HEIGHT} --W ${WIDTH} --seed ${SEED} --n_iter 1 --ddim_steps 50 --skip_grid --n_samples 1 --outdir ${TMPDIR} --prompt "${GEN}"

# Now for upscaling
# deactivate
# cd ../Real-ESRGAN
# . env/bin/activate

# python inference_realesrgan.py --face_enhance -n RealESRGAN_x4plus -i ${TMPDIR}/samples/0000.png -o ${TMPDIR}

convert ${TMPDIR}/*/00000.png ${OUTFILE}

exiftool -overwrite_original -description="${PROMPT}" -software='Stable Diffusion v1.4' -make="--seed ${SEED}" -artist="${STYLE}" ${OUTFILE}

rm -rf ${TMPDIR}
